### ISSUE TITLE
Environmentalist - carbon footprint

### ISSUE THREAD

**Issue by yeonwooklee** [code4policy/2024-a4-Transport-and-Walking#3]

**Comment by yeonwooklee** [comment]
As an environmentalist 
I want to live in the place with the most bike trails, 
so that i can be so i can reduce my carbon footprint.

**Comment by Jalutka** [comment]
This user story is probably not feasible for the level of data that we have on rails/trails usage.

[x]Independent--different than other indicators
[x]Negotiable -  yes, it could be different ways to do this
[x]Valuable - yes, meaningful to user's sense of value
[x]Estimable -yes there are lots of websites about estimating (https://www.carbonfootprint.com/calculator.aspx) 
[NO]Small (?)---NO
[?]Testable --this would require user to track their usage and then report it back to the application, too big for this scope, especially since we are thinking of just map data

**Definition of done:**

Be able to compare the carbon footprint of their bike commute vs that of a car

**Alternative story**

https://www.railstotrails.org/greatamericanrailtrail/

OR there already exists a commute carbon calculator;

https://transportation-forms.stanford.edu/cost/

Maybe there is a way to combine the stanford calculator with a Google Maps type thing

Alternative story?

As a tech and environmentlally savvy commuter in X city
I want to see the carbon footprint of my different options of commuting
so that I can compare the time/convenience/environmental impact of my commute

[?]Independent--Not really, would depend on other variables, like getting the map data
[x]Negotiable -  yes, it could be different ways to do this
[x]Valuable - yes, meaningful to user's sense of value
[x]Estimable -yes there are lots of websites about estimating (https://www.carbonfootprint.com/calculator.aspx) 
[NO]Small (?)---NO
[?]Testable --yes
