### ISSUE TITLE
[1] Biker - Web page

### ISSUE THREAD

**Issue by yeonwooklee** [code4policy/2024-a4-Transport-and-Walking#4]

**Comment by yeonwooklee** [comment]
As a biker I want to build a web page so that I can show states and available trails Biker

**Comment by Leks10** [comment]
As a biker I want to have a web page that displays cities and available trails so that I can search for cities and trials close to me. 
[ x ] Independent
[ x ] Negotiable
[ x ] Valuable
[ x ] Estimable
[ x ] Small
[ x ] Testable

Definition of Done:
All cities and trials are test and made available for search.
