### ISSUE TITLE
Local government - biking policy

### ISSUE THREAD

**Issue by yeonwooklee** [code4policy/2024-a4-Transport-and-Walking#6]

**Comment by yeonwooklee** [comment]
As a local government, I want to check if our region has enough infrastructure for biking so that I can make a better biking policy. Local government - biking policy

**Comment by Leks10** [comment]
As a local government official,
I want to have a dashboard to display information that our region's infrastructure for biking
so that I can have insight to make a better biking policy.

[ x ] Independent
[ ? ] Negotiable yes but may need some more input
[ x ] Valuable
[ x ] Estimable
[ x ] Small
[ x ] Testable

Definition of Done:
All regional biking infrastructure can be seen on the dashboard.
