### ISSUE TITLE
[2] Biking enthusiast - move to the state

### ISSUE THREAD

**Issue by yeonwooklee** [code4policy/2024-a4-Transport-and-Walking#7]

**Comment by yeonwooklee** [comment]
As a biking enthusiast, 
I want to move to the state with the most developed trails 
so that I can feel free to bike.

**Comment by jianingwww** [comment]
Improved version: As a biking enthusiast, I want to relocate to a state with well-defined and well-maintained biking trails, such as those featuring paved paths, mountain biking trails, and scenic routes, so that I can enjoy a high-quality biking experience.

[x]Independent
[x]Negotiable
[x]Valuable
[x]Estimable
[]Small (?)
[x]Testable

Definition of done:
1. Defined criteria for well-maintained biking trails (paved/protected/...)
2. Be able to view the map and find states with the most developed trails

**Comment by Jalutka** [comment]
HEre is a website that looks like it kind of does this:  https://cityratings.peopleforbikes.org/
