### ISSUE TITLE
[4] Bike shop owner - visualization listing cities and trails

### ISSUE THREAD

**Issue by yeonwooklee** [code4policy/2024-a4-Transport-and-Walking#8]

**Comment by yeonwooklee** [comment]
As bike shop owner 
I want to have a visualization listing cities and trails 
so that I can target cities with most trails.

**Comment by Jalutka** [comment]
Improved statement

As a representative of a national bike store chain (Trek for example) considering expansion,
I want to have a visualization comparing states attractiveness to investment (based on undeveloped trails, disposable income, public policy friendliness, environmental care, etc),
So that I can maximize my return on investment

[]Independent--different than other indicators
[x]Negotiable -  yes, it could be different ways to do this
[]Valuable - yes, meaningful to user's sense of value
[]Estimable -yes, look at the various data sets, see how we could compare them, 
[]Small (?)---we could limit it to a region
[?]Testable -- yes

**Definition of Done**

-A bike shop chain can easily compare states based on their income/existing bike infrastructure/public policy friendlinessexpansion of bike infrastructure/and other factors  an area is compared with other potential areas to expand
-

I am not sure if this is really any different than what a biker would want?  except that the motivation is potential return on investment for opening a new bike shop.  Maybe need to align this with other data sets, such as:

- **Amount of disposable income per state** (https://www-statista-com.ezp-prod1.hul.harvard.edu/statistics/303534/us-per-capita-disposable-personal-income/
- **Public Policy friendliness-Funding** (https://data.bikeleague.org/show-your-data/state-data/topic-ix-funding-for-biking-walking/)
- **Public Policy Friendliness Bike Related Plans**https://data.bikeleague.org/show-your-data/state-data/section-vii-plans-policies/

An idea for the website:  Same US state map infrastructure, we assign a score and color coding based on all of the data sets 

It is kind of like this one:  https://bikeleague.org/bfa/states/ranking/

But with added economic factors and integrating the mileage of existing and potential rail to trail
