### ISSUE TITLE
Biker - create bike groups in cities

### ISSUE THREAD

**Issue by yeonwooklee** [code4policy/2024-a4-Transport-and-Walking#9]

**Comment by yeonwooklee** [comment]
As a biker
I want to create bike groups in cities with trails
so that bikers can join for social networking.

**Comment by jianingwww** [comment]
Improved version: As a biker, I want to know the specific cities with the most bikers, determined by factors like biking events, bike-friendly infrastructure, and active biking communities, so that I can create or join bike groups.

[x]Independent
[x]Negotiable
[x]Valuable
[x]Estimable
[x]Small 
[x]Testable

Definition of done:

1. Reliable data identifying cities with the most bikers

**Comment by Jalutka** [comment]
this could be another thing to pull into the dashboard for the company
